version: "3.8"

services:
  db:
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
        - "5432:5432"
    volumes:
        - "./pgdata:/var/lib/postgresql/data/"
